version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: "${GITLAB_HOST}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOST}:${GITLAB_HTTP_PORT}${GITLAB_HTTP_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        puma['port'] = 8081
        gitlab_workhorse['auth_backend'] = "http://localhost:8081"
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
        gitlab_rails['initial_shared_runners_registration_token'] = "${REGISTRATION_TOKEN}"
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
          main:
            label: 'LDAP'
            host: '${LDAP_SERVER}'
            port: ${LDAP_PORT}
            uid: '${LDAP_UID}'
            base: '${LDAP_BASE}'
            bind_dn: '${LDAP_BIND_DN}'
            password: '${LDAP_PASSWORD}'
            encryption: 'plain'
        EOS
    ports:
      - "${GITLAB_HTTP_PORT}:8080"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      mode: replicated
      replicas: 1 # Diese Zahl kannst du dynamisch ändern
    environment:
      - CI_SERVER_URL=http://${GITLAB_HOST}:${GITLAB_HTTP_PORT}${GITLAB_HTTP_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN} # Ersetze <TOKEN> durch deinen tatsächlichen Token
    volumes:
      - './runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
