services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: "${GITLAB_HOST}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST}:${GITLAB_HTTPS_PORT}${GITLAB_HTTP_URL}/'
        nginx['listen_port'] = 80
        nginx['listen_port'] = 443
        nginx['listen_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        puma['port'] = 8081
        gitlab_workhorse['auth_backend'] = "http://localhost:8081"
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
        gitlab_rails['initial_shared_runners_registration_token'] = "${REGISTRATION_TOKEN}"
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
          main:
            label: 'LDAP'
            host: '${LDAP_SERVER}'
            port: ${LDAP_PORT}
            uid: '${LDAP_UID}'
            base: '${LDAP_BASE}'
            bind_dn: '${LDAP_BIND_DN}'
            password: '${LDAP_PASSWORD}'
            encryption: 'plain'
        EOS
    ports:
      - "${GITLAB_HTTP_PORT}:80" # Gitlab direkt über HTTP
      - "${GITLAB_HTTPS_PORT}:443" # Gitlab direkt über HTTPS
      - "${GITLAB_SSH_PORT}:22" # Gitlab direkt über SSH (for git operations)
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
      - "./ssl/${GITLAB_HOST}.crt:/etc/gitlab/ssl/gitlab.crt:ro"
      - "./ssl/${GITLAB_HOST}.key:/etc/gitlab/ssl/gitlab.key:ro"
    networks:
      - gitlab-network
    labels:
      - "traefik.enable=true"
      # HTTP Router configuration
      #- "traefik.http.routers.gitlab-http.rule=Host(`${GITLAB_HOST}`) && PathPrefix(`${GITLAB_HTTP_URL}`)"
      #- "traefik.http.routers.gitlab-http.entrypoints=web"
      #- "traefik.http.services.gitlab-http.loadbalancer.server.port=${GITLAB_HTTP_PORT}"
      # HTTPS Router configuration
      - "traefik.http.routers.gitlab-https.rule=Host(`${GITLAB_HOST}`) && PathPrefix(`${GITLAB_HTTP_URL}`)"
      - "traefik.http.routers.gitlab-https.entrypoints=websecure"
      - "traefik.http.routers.gitlab-https.tls=true"
      - "traefik.http.services.gitlab-https.loadbalancer.server.port=${GITLAB_HTTPS_PORT}"
      # SSH Router configuration
      - "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-service"
      - "traefik.tcp.services.gitlab-ssh-service.loadbalancer.server.port=22"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      mode: replicated
      replicas: 1 # Diese Zahl kannst du dynamisch ändern
    environment:
      - CI_SERVER_URL=http://${GITLAB_HOST}:${GITLAB_HTTP_PORT}${GITLAB_HTTP_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN} # Ersetze <TOKEN> durch deinen tatsächlichen Token
    volumes:
      - './runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

  traefik:
    image: traefik:latest
    container_name: gitlab-traefik
    restart: always
    ports:
      - 18000:8080 # Traefik Dashboard
      - 18080:18080 # Gitlab HTTP über Traefik
      - 18443:18443 # Gitlab HTTPS über Traefik
      - 18022:18022 # Gitlab-SSH über Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml #Static traefik configuration (entrypoints, providers and log)
      - ./traefik/dynamic_conf.toml:/etc/traefik/dynamic_conf.toml #Dynamic traefik configuration (https redirection, tls and certificates)
      - "./ssl/${GITLAB_HOST}.crt:/etc/certs/server.crt"
      - "./ssl/${GITLAB_HOST}.key:/etc/certs/server.key"
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
