global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":18080"
  websecure:
    address: ":18443"
  ssh:
    address: ":18022"

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.toml"
  docker:
    watch: true
    network: gitlab-network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true
  debug: true
  insecure: true
  
log:
  # filePath: "/logs/traefik.log"
  level: DEBUG

serversTransport:
  InsecureSkipVerify: true
